name: Build Twitch Chat

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}
          build-scan-terms-of-use-agree: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}

      - name: Build with Gradle Wrapper
        run: |-
          ./gradlew build --scan
          ls -la build/libs/

      - name: Save Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Twitch Chat Bridge
          path: ${{ github.workspace }}/build/libs
